version: "3.1"

services:
  api:
    restart: always
    container_name: kata_api
    build: .
    command: bash -c "python kata/manage.py crontab add && cron start && gunicorn -c gunicorn.py --chdir /kata/kata kata.wsgi:application"
    ports:
      - '9001:5000'
    volumes:
      - .:/kata
      - ./gunicorn.py:/gunicorn.py
    environment:
      - TZ=Asia/Taipei
    networks:
      - kata-api

  mongodb:
    image: mongo
    hostname: kata_api_mongodb
    container_name: kata_api_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: line
      MONGO_INITDB_ROOT_PASSWORD: 1qaz@WSX
      MONGO_INITDB_DATABASE: kata_api_db
    logging:
      driver: json-file
      options:
        max-size: 50m
    restart: always
    volumes:
      - ./DATA/kata/mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - kata-api


networks:
  kata-api:
    external: true